#pragma once

enum AV_ERROR
{
    NO_ERROR = 0,
    STREAM_OPEN_FAILED,
    STREAM_INIT_FAILED,
    VIDEO_STREAM_NOT_FOUND,
    CODEC_INIT_FAILED,
    CODEC_OPEN_FAILED,
    PACKET_DECODE_FAILED,
    FRAME_DECODE_FAILED,
    INIT_BUFFER_FAILED,
    SCALER_CONTEXT_UNINITIALIZED,
    FRAME_FORMAT_FAILED,
    FORMAT_CONTEXT_UNINITIALIZED,
    OUTPUT_FILE_OPEN_FAILED,
    HEADER_WRITE_FAILED,
    WRITE_FRAME_FAILED
};
